name: PullRequest GitHub Runner - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch

  pull_request:
    branches: [ main ]
#env:
  #MLM_LICENSE_TOKEN: ${{ secrets.MYMATLABTOKEN_NONENV }}

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Craete Webview
    runs-on: ubuntu-latest
    environment: myMATLABenv # This links the job to the environment
    env:
      MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}  # Uses the environment secret
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Simulink
            Simulink_Report_Generator
            MATLAB_Report_Generator
          cache: true
          version: R2024b  
      - name: Start display server
        run: |
         sudo apt-get install -y xvfb
         Xvfb :99 &
         export DISPLAY=:99
         echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v2
        with:
          command: branch ="${{ github.head_ref }}", diffGitHub_pullrequest(branch)
      - name: Create Project Webview
        uses: matlab-actions/run-command@v2
        with:
          command: genWebView
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v4
        with:
           name: model_details
           path: |
            ${{ github.workspace }}/*.html
            ${{ github.workspace }}/*.zip


#   Copyright 2022-2025 The MathWorks, Inc.
